### ISSUE TITLE
Travis CI throws error OAuth2 authentication requires a token

### ISSUE THREAD

**Issue by gribok** [soroushchehresa/awesome-coronavirus#32]
The CI pipelines failed due to an authentication error.

```
$ node src/index.js
/home/travis/build/soroushchehresa/awesome-coronavirus/node_modules/github/lib/index.js:334
                throw new Error("OAuth2 authentication requires a token or key & secret to be set");
                ^
Error: OAuth2 authentication requires a token or key & secret to be set
    at module.exports.authenticate (/home/travis/build/soroushchehresa/awesome-coronavirus/node_modules/github/lib/index.js:334:23)
    at Object.<anonymous> (/home/travis/build/soroushchehresa/awesome-coronavirus/src/index.js:33:8)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run build" exited with 1.
cache.2
store build cache
```

Build-Log:
https://travis-ci.org/github/soroushchehresa/awesome-coronavirus/builds/664355725

**Comment by soroushchehresa** [comment]
@gribok You should add your GitHub API token as `GITHUB_AUTH_TOKEN` in `.env` file and then run the build script.

**Comment by gribok** [comment]
It isn't declare in `contribution` guide.
Maybe it could be added.
